// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcNwhBkSYPYL9Jo6zlYCvYCTeUt657uts',
    appId: '1:1008199751311:web:9ed5e890a207c71af8c2fa',
    messagingSenderId: '1008199751311',
    projectId: 'instaclosachin',
    authDomain: 'instaclosachin.firebaseapp.com',
    storageBucket: 'instaclosachin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRVOLTvOayx-0CpGnyH2rFsDR9frkppUg',
    appId: '1:1008199751311:android:8d81730f9fbccf86f8c2fa',
    messagingSenderId: '1008199751311',
    projectId: 'instaclosachin',
    storageBucket: 'instaclosachin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjNNNYBE8GzMqF9I9F9YFSKnCcwXyDXBU',
    appId: '1:1008199751311:ios:c03acd6e810d3910f8c2fa',
    messagingSenderId: '1008199751311',
    projectId: 'instaclosachin',
    storageBucket: 'instaclosachin.appspot.com',
    iosClientId: '1008199751311-0jgo70qcmii0v591o595k9b37d4fhfl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClosachin',
  );
}
